[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "pip install -r backend/requirements-base.txt",
  "pip install --prefer-binary spacy",
  "python -m spacy download en_core_web_sm"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
